version: '3'
services:
  mysql:
    image: mariadb:latest
    container_name: app_base_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: 123456
      TZ: America/Lima

  php-fpm:
    build: ./docker/php-fpm
    container_name: app_base_php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html/
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql

  nginx:
    image: nginx
    container_name: app_base_nginx
    ports:
      - 80:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html/
      - ./docker/config/:/etc/nginx/conf.d/
      - ./docker/logs:/var/log/nginx
